export const MAIN_CHANNEL = 'general'

export const AUTODOWNLOAD_SIZE_LIMIT = 20971520 // 20 MB

export const BASE_NOTIFICATION_CHANNEL = '_BASE_NOTIFICATION_'
export const RICH_NOTIFICATION_CHANNEL = '_RICH_NOTIFICATION_'
export const WEBSOCKET_CONNECTION_CHANNEL = '_WEBSOCKET_CONNECTION_'
export const INIT_CHECK_CHANNEL = '_INIT_CHECK_'
