AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Subnets:
    Type: String

  TaskCpu:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html

  TaskMemory:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html

  TorTestImage:
    Type: String

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
  
  EventECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
      Policies:
      - PolicyName: AmazonECSTaskExecutionRolePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - ecs:RunTask
            Resource:
              - !Ref TorConnectionTestTaskDefinition
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - '*'

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Policies:
      - PolicyName: AmazonECSTaskExecutionRolePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ec2:DescribeNetworkInterfaces
            - ecs:DescribeTasks
            - s3:*
            Resource: '*'


  TorConnectionTestTaskRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule rule for tor connection test"
      Name: !Sub tor-connection-task-schedule-rule
      State: ENABLED
      ScheduleExpression: cron(0/10 * * * ? *)
      Targets:
        - Arn: !GetAtt ECSCluster.Arn
          Id: ScheduledTask
          RoleArn: !GetAtt EventECSExecutionRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref TorConnectionTestTaskDefinition
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                Subnets: !Split
                  - ','
                  - !Ref Subnets

  TorConnectionTestVanguardOffTaskRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule rule for tor connection test without vanguards"
      Name: !Sub tor-connection-task-vanguard-off-schedule-rule
      State: ENABLED
      ScheduleExpression: cron(0/10 * * * ? *)
      Targets:
        - Arn: !GetAtt ECSCluster.Arn
          Id: ScheduledTask
          Input: !Sub '{ "containerOverrides": [{"name": "tor-connection-test", "environment": [{"name":"VANGUARDS_ENABLED","value":0}]}]}'
          RoleArn: !GetAtt EventECSExecutionRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref TorConnectionTestTaskDefinition
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                Subnets: !Split
                  - ','
                  - !Ref Subnets

  TorConnectionTestTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-PerformanceData
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
      - FARGATE
      Memory: !Ref TaskMemory
      Cpu: !Ref TaskCpu
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Image: !Ref TorTestImage
          Essential: true
          Memory: !Ref TaskMemory
          Name: tor-connection-test
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref LogGroup
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: tor-connection-test

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}/tor-connection-test