/**
 * Handles lockbox-related chain operations
 */
import { InviteLockboxMetadata } from './types'
import { ChainServiceBase } from '../chainServiceBase'
import { SigChain } from '../../sigchain'
import { KeysetWithSecrets, Lockbox, createKeyset } from '@localfirst/auth'
import { createLogger } from '../../../common/logger'
import { RoleName } from '../roles/roles'
import { hash } from '@localfirst/crypto'

const logger = createLogger('auth:lockbox')

class LockboxService extends ChainServiceBase {
  constructor(sigChain: SigChain) {
    super(sigChain)
  }

  /**
   * Generate a keyset from an invite seed for encrypting/decrypting a lockbox
   *
   * @param seed Invite seed generated by the owner (this is the string included in the invite link)
   * @param salt Random salt generated at the time of invite creation, used to create a key scope name
   * @returns Object containing the key scope name and the keys created using the seed
   */
  public generateLockboxKeys(seed: string, salt: string): InviteLockboxMetadata {
    logger.debug('Generating keys from invite seed')
    const name = hash(salt, seed)
    const keys = createKeyset({ type: 'INVITE_LOCKBOX', name }, seed)
    return {
      id: name,
      keys,
    }
  }

  /**
   * Create a lockbox containing the MEMBER role keys accessible using the invite seed
   *
   * @param seed Invite seed generated by the owner (this is the string included in the invite link)
   * @param salt Random salt generated at the time of invite creation, used to create a key scope name
   * @returns Lockbox containing the MEMBER role keys encrypted using the invite seed
   */
  public createInviteLockboxes(seed: string, salt: string): Lockbox[] {
    logger.debug('Creating lockbox containing MEMBER role keys encrypted to invite-based keys')
    if (this.sigChain.team == null) {
      throw new Error('Error while creating invite lockbox - No team')
    }
    if (!this.sigChain.roles.memberHasRole(this.sigChain.context.user.userId, RoleName.MEMBER)) {
      throw new Error('Error while creating invite lockbox - User is missing MEMBER role')
    }
    const inviteKeyset = this.generateLockboxKeys(seed, salt)
    return this.sigChain.team.createLockbox(RoleName.MEMBER, inviteKeyset.keys)
  }

  /**
   * Decrypt the invite lockbox using the invite seed-based keys and return the MEMBER role keys
   *
   * @param seed Invite seed generated by the owner (this is the string included in the invite link)
   * @param salt Random salt generated at the time of invite creation, used to create a key scope name
   * @returns MEMBER role keys pulled from invite lockbox
   */
  public openInviteLockbox(seed: string, salt: string): KeysetWithSecrets {
    logger.debug('Opening lockbox containing MEMBER role keys encrypted to invite-based keys')
    if (this.sigChain.team == null) {
      throw new Error('Error while opening invite lockbox - No team')
    }
    if (this.sigChain.roles.memberHasRole(this.sigChain.context.user.userId, RoleName.MEMBER)) {
      throw new Error('Error while opening invite lockbox - Already has MEMBER role')
    }
    const inviteKeyset = this.generateLockboxKeys(seed, salt)
    const roleKeys = this.sigChain.team.roleKeys(RoleName.MEMBER, undefined, inviteKeyset.keys)
    return roleKeys
  }
}

export { LockboxService }
