// Generates screens/OnboardingFlow.stories.tsx from figma/flow.json.
// Storybook derives a story's id from the EXPORT NAME (storyNameFromExport → toId),
// not from `storyName`, so export identifiers are chosen so the derived id equals
// `onboarding-flow--<slug>`, and that equality is asserted here with @storybook/csf.
const fs = require('fs'); const path = require('path')
const { toId, storyNameFromExport } = require('@storybook/csf')
const TITLE = 'Onboarding flow'
const flowPath = path.join(__dirname, '..', 'figma', 'flow.json')
const flow = JSON.parse(fs.readFileSync(flowPath, 'utf8'))
// 'ios-photo-gallery-2811-2501' -> 'IosPhotoGallery_2811_2501' : words PascalCased, numeric runs underscored
const exportFor = slug => slug.split('-').map(w => (/^\d+$/.test(w) ? '_' + w : w[0].toUpperCase() + w.slice(1))).join('')
const expectId = slug => `${toId(TITLE, 'x').split('--')[0]}--${slug}`
const rows = []
for (const f of flow.frames) {
  const exp = exportFor(f.slug); const id = toId(TITLE, storyNameFromExport(exp)); const want = expectId(f.slug)
  if (id !== want) { console.error(`ID MISMATCH ${f.slug}: export ${exp} -> ${id}, wanted ${want}`); process.exit(1) }
  f.id = id; f.export = exp; rows.push(f)
}
const mapId = toId(TITLE, storyNameFromExport('AllStages'))
flow.mapId = mapId
fs.writeFileSync(flowPath, JSON.stringify(flow, null, 1))
const L = [
  '// GENERATED by design-system/flow/gen.cjs from figma/flow.json — do not hand-edit.',
  '// One story per screen reachable from "Get started" via the prototype\'s own links.',
  '// Export names are chosen so Storybook\'s derived id equals `onboarding-flow--<slug>`; gen.cjs asserts it.',
  "import React from 'react'", '', "import flowJson from '../figma/flow.json'",
  "import { DesktopDesigns, DesktopStoryboard, Flow, FlowMap, FLOW_TITLE, Stage } from '../flow/FigmaFlow'", '',
  'const flow = flowJson as Flow', 'const frame = (slug: string) => flow.frames.find(f => f.slug === slug)!', '',
  'export default {', '  title: FLOW_TITLE,', "  parameters: { layout: 'fullscreen', chromatic: { disableSnapshot: true } },", '}', '',
  'export const AllStages = () => <FlowMap flow={flow} />', "AllStages.storyName = '— all stages —'", '',
  'export const DesktopDesigns_ = () => <DesktopDesigns flow={flow} />', "DesktopDesigns_.storyName = 'Desktop — designs'", '',
  'export const DesktopStoryboard_ = () => <DesktopStoryboard />', "DesktopStoryboard_.storyName = 'Desktop — storyboard (Feb 2025)'", '',
]
for (const f of rows) L.push(`export const ${f.export} = () => <Stage flow={flow} frame={frame(${JSON.stringify(f.slug)})} />`, `${f.export}.storyName = ${JSON.stringify(f.display)}`, '')
fs.writeFileSync(path.join(__dirname, '..', 'screens', 'OnboardingFlow.stories.tsx'), L.join('\n'))
// gate rows: id<TAB>export-name needle
fs.writeFileSync('/mnt/storage/holmes-tmp/gate-ids.txt', [[mapId, 'AllStages'], [toId(TITLE, storyNameFromExport('DesktopDesigns_')), 'DesktopDesigns_'], [toId(TITLE, storyNameFromExport('DesktopStoryboard_')), 'DesktopStoryboard_'], ...rows.map(f => [f.id, f.export])].map(r => r.join('\t')).join('\n') + '\n')
console.log(`generated ${rows.length} stories; ids verified with @storybook/csf; map id ${mapId}`)
