name: 'Prepare app build'

inputs:
  source-path:
    description: 'OS name (linux | darwin | win32)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Bundle backend for production
      run: cd packages/backend && npm run webpack:prod
      shell: bash

    - name: "Pull tor binary"
      if: ${{ inputs.source-path == 'linux' || inputs.source-path == 'darwin' }}
      run: cd packages/desktop && export SOURCE_PATH=${{ inputs.source-path }} && npm run copyBinaries && npm run setMainEnvs
      shell: bash

    - name: "Pull tor binary for Windows"
      if: ${{ inputs.source-path == 'win32' }}
      run: cd packages/desktop && export SOURCE_PATH=${{ inputs.source-path }} && npm run copyBinariesWin && npm run setMainEnvs
      shell: bash

    - name: "Verify test mode setup"
      run: echo $TEST_MODE
      shell: bash

    - name: "Verify bucket setup"
      run: echo $S3_BUCKET
      shell: bash

    - name: "Build the project"
      run: npx lerna run build:prod --scope quiet
      shell: bash
