name: 'Prepare app build'

inputs:
  source-path:
    description: 'OS name (linux | darwin | win32)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@master
      with:
        node-version: "12"

    - name: Install electron-builder globally
      run: npm i -g electron-builder@22.10.5
      shell: bash

    - name: "Pull tor binary"
      run: cd packages/frontend && export SOURCE_PATH=${{ inputs.source-path }} && npm run copyBinaries
      shell: bash
    
    - name: "Verify Sentry setup"
      run: echo $REACT_APP_ENABLE_SENTRY
      shell: bash
    
    - name: "Verify bucket setup"
      run: echo $S3_BUCKET
      shell: bash

    - name: "Build the project"
      run: lerna run build:prod --scope quiet
      shell: bash