import { DisplayableMessage } from '@quiet/types'

export const users = {
  vader: { nickname: 'vader', userId: 'vaderUserId' },
  yoda: { nickname: 'yoda', userId: 'yodaUserId' },
  obi: { nickname: 'obi', userId: 'obiUserId' },
  wookie: { nickname: 'wookie', userId: 'wookieUserId' },
  leia: { nickname: 'leia', userId: 'leiaUserId' },
  chad: { nickname: 'chad', userId: 'chadUserId' },
  windoo: { nickname: 'windoo', userId: 'windooUserId' },
  luke: { nickname: 'luke', userId: 'lukeUserId' },
  anakin: { nickname: 'anakin', userId: 'anakinUserId' },
  alice: { nickname: 'alice', userId: 'aliceUserId' },
  john: { nickname: 'john', userId: 'johnUserId' },
}

export const mock_messages = (message: DisplayableMessage | null = null) => {
  let placeholder: DisplayableMessage = {
    id: '32',
    type: 1,
    media: undefined,
    message: '*heavy breathing*',
    createdAt: 0,
    date: '12:46',
    nickname: users.vader.nickname,
    isRegistered: true,
    isDuplicated: false,
    userId: users.vader.userId,
  }

  if (message !== null) {
    placeholder = message
  }

  const messages: {
    count: number
    groups: { [day: string]: DisplayableMessage[][] }
  } = {
    count: 32,
    groups: {
      '26 Oct': [
        [
          {
            id: '1',
            type: 1,
            message: 'Messages more there should be',
            createdAt: 0,
            date: '12:46',
            nickname: users.yoda.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.yoda.userId,
          },
        ],
        [
          {
            id: '2',
            type: 1,
            message: 'I Agree',
            createdAt: 0,
            date: '12:46',
            nickname: users.obi.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.obi.userId,
          },
          {
            id: '3',
            type: 1,
            message: 'Of course, I Agree',
            createdAt: 0,
            date: '12:46',
            nickname: users.obi.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.obi.userId,
          },
        ],
        [
          {
            id: '4',
            type: 1,
            message: 'Wrough!',
            createdAt: 0,
            date: '12:46',
            nickname: users.wookie.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.wookie.userId,
          },
        ],
        [
          {
            id: '5',
            type: 1,
            message: 'Yeah!',
            createdAt: 0,
            date: '12:46',
            nickname: users.leia.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.leia.userId,
          },
        ],
        [
          {
            id: '6',
            type: 1,
            message: 'The more messages the better',
            createdAt: 0,
            date: '12:46',
            nickname: users.luke.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.luke.userId,
          },
        ],
        [
          {
            id: '7',
            type: 1,
            message: 'We cannot grant you the rank of messager',
            createdAt: 0,
            date: '12:46',
            nickname: users.windoo.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.windoo.userId,
          },
        ],
        [
          {
            id: '8',
            type: 1,
            message:
              'deathhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhstarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdeathstartttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
            createdAt: 0,
            date: '12:46',
            nickname: users.vader.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.vader.userId,
          },
        ],
      ],
      '27 Oct': [
        [
          {
            id: '9',
            type: 1,
            message: 'Luke, I am your father!',
            createdAt: 0,
            date: '12:40',
            nickname: users.chad.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.chad.userId,
          },
          {
            id: '10',
            type: 1,
            message: "That's impossible!",
            createdAt: 0,
            date: '12:41',
            nickname: users.chad.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.chad.userId,
          },
          {
            id: '11',
            type: 1,
            message: 'Nooo!',
            createdAt: 0,
            date: '12:45',
            nickname: users.chad.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.chad.userId,
          },
        ],
        [
          {
            id: '12',
            type: 1,
            message: 'Uhuhu!',
            createdAt: 0,
            date: '12:46',
            nickname: users.anakin.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.anakin.userId,
          },
        ],
        [
          {
            id: '13',
            type: 1,
            message: 'Why?',
            createdAt: 0,
            date: '12:46',
            nickname: users.anakin.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.anakin.userId,
          },
        ],
        [
          {
            id: '14',
            type: 1,
            message: 'Messages more there should be',
            createdAt: 0,
            date: '12:46',
            nickname: users.yoda.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.yoda.userId,
          },
        ],
        [
          {
            id: '15',
            type: 1,
            message: 'I Agree',
            createdAt: 0,
            date: '12:46',
            nickname: users.obi.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.obi.userId,
          },
          {
            id: '16',
            type: 1,
            message: 'Of course, I Agree',
            createdAt: 0,
            date: '12:46',
            nickname: users.obi.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.obi.userId,
          },
        ],
        [
          {
            id: '17',
            type: 1,
            message: 'Wrough!',
            createdAt: 0,
            date: '12:46',
            nickname: users.wookie.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.wookie.userId,
          },
        ],
        [
          {
            id: '18',
            type: 1,
            message: 'Yeah!',
            createdAt: 0,
            date: '12:46',
            nickname: users.leia.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.leia.userId,
          },
        ],
        [
          {
            id: '19',
            type: 1,
            message: 'The more messages the better',
            createdAt: 0,
            date: '12:46',
            nickname: users.luke.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.luke.userId,
          },
        ],
        [
          {
            id: '20',
            type: 1,
            message: 'We cannot grant you the rank of messager',
            createdAt: 0,
            date: '12:46',
            nickname: users.windoo.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.windoo.userId,
          },
        ],
        [
          {
            id: '21',
            type: 1,
            message:
              'deathhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhstarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdeathstartttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
            createdAt: 0,
            date: '12:46',
            nickname: users.vader.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.vader.userId,
          },
        ],
      ],
      '28 Oct': [
        [
          {
            id: '22',
            type: 1,
            message: 'Hello',
            createdAt: 0,
            date: '28 Oct, 10:00',
            nickname: users.alice.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.alice.userId,
          },
          {
            id: '23',
            type: 1,
            message:
              "How are you? My day was awesome. I removed a lot of unused props from container and I simplified code a lot. I like coding, coding is like building things with LEGO. I could admit it's a little bit harder and there's a lot that can go wrong but I like it anyway.",
            createdAt: 0,
            date: '28 Oct, 10:01',
            nickname: users.alice.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.alice.userId,
          },
        ],
        [
          {
            id: '24',
            type: 1,
            message: 'Great, thanks!',
            createdAt: 0,
            date: '28 Oct, 10:02',
            nickname: users.john.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.john.userId,
          },
        ],
      ],
      Today: [
        [
          {
            id: '25',
            type: 1,
            message: 'Luck, I am your father!',
            createdAt: 0,
            date: '12:40',
            nickname: users.chad.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.chad.userId,
          },
          {
            id: '26',
            type: 1,
            message: "That's impossible!",
            createdAt: 0,
            date: '12:41',
            nickname: users.chad.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.chad.userId,
          },
          {
            id: '27',
            type: 1,
            message: 'Nooo!',
            createdAt: 0,
            date: '12:45',
            nickname: users.chad.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.chad.userId,
          },
        ],
        [
          {
            id: '28',
            type: 1,
            message: 'Uhuhu!',
            createdAt: 0,
            date: '12:46',
            nickname: users.anakin.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.anakin.userId,
          },
        ],
        [
          {
            id: '29',
            type: 1,
            message: 'Why?',
            createdAt: 0,
            date: '12:46',
            nickname: users.anakin.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.anakin.userId,
          },
        ],
        [
          {
            id: '30',
            type: 1,
            message: 'Messages more there should be',
            createdAt: 0,
            date: '12:46',
            nickname: users.yoda.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.yoda.userId,
          },
        ],
        [
          {
            id: '31',
            type: 1,
            message: 'I Agree',
            createdAt: 0,
            date: '12:46',
            nickname: users.obi.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.obi.userId,
          },
        ],
        [placeholder],
        [
          {
            id: '33',
            type: 1,
            message: 'Use the force, Luke!',
            createdAt: 0,
            date: '12:46',
            nickname: users.vader.nickname,
            isRegistered: true,
            isDuplicated: false,
            userId: users.vader.userId,
          },
        ],
      ],
    },
  }

  return messages
}
