/**
 * OrbitDB identity provider that uses LFA for verification/signing rather than the standard
 * OrbitDB model of identity.
 *
 * NOTE: This doesn't store ANY identity data in OrbitDB, all identification is handled
 * ad hoc using the sigchain.
 */

import { IdentityProvider } from '@orbitdb/core'
import { LFA_IDENTITY_PROVIDER_TYPE } from './const'
import { Injectable } from '@nestjs/common'
import { SigChainService } from '../../../../auth/sigchain.service'
import {
  LFAIdentity,
  LFAIdentityProviderGetIdError,
  LFAIdentityProviderSignError,
  LFAIdentityProviderVerifyError,
  LFAUserAndChain,
  SignatureWithTeamId,
  SignedEnvelopeWithTeamId,
} from './types'
import { Member } from '@localfirst/auth'
import { hash } from '@localfirst/crypto'
import { createLogger } from '../../../../common/logger'
import { randomUUID } from 'crypto'
import { Serializer } from '../../../../common/serializer.service'
import { SerializerEncodingType } from '@quiet/types'
import * as uint8arrays from 'uint8arrays'

@Injectable()
class LFAIdentityProvider implements IdentityProvider {
  private readonly logger = createLogger('orbitdb:identity:lfa:provider')

  constructor(
    private readonly serializer: Serializer,
    private readonly sigchainService: SigChainService
  ) {}

  /**
   * Type of the identity provider
   */
  get type(): string {
    return LFA_IDENTITY_PROVIDER_TYPE
  }

  /**
   * Verify and return the user ID from the sigchain
   *
   * @param userId LFA user ID
   * @param teamId LFA team ID
   * @returns User ID that is verified to be on the chain
   */
  public async getId(userId: string, teamId: string): Promise<string> {
    try {
      const { user } = this.getUserAndChain(userId, teamId)
      return user!.userId
    } catch (e) {
      throw new LFAIdentityProviderGetIdError(e)
    }
  }

  /**
   * Generate a static signature using your user's keys from the sigchain to be added to the identity
   * record
   *
   * NOTE: We don't use these signatures for real so we just return an arbitrary string
   *
   * TODO: Actually do something with this signature or delete the signature logic
   *
   * @param userId LFA user ID
   * @param teamId LFA team ID
   * @returns Signature generated using this user's keys
   */
  public async signIdentity(userId: string, teamId: string): Promise<string> {
    try {
      // TODO: replace this with `sign` if we end up signing the identity records themselves
      const { user, sigchain } = this.getUserAndChain(userId, teamId)
      const userFromContext = sigchain.context.user
      if (userFromContext.userId !== user.userId || userFromContext.keys.signature.publicKey != user.keys.signature) {
        throw new Error('User ID and/or public signing key does not match context user')
      }
      // return a random string because this static identity signature is unused
      return randomUUID()
    } catch (e) {
      throw new LFAIdentityProviderSignError(e)
    }
  }

  /**
   * Validate a given identity from OrbitDB against the sigchain
   *
   * @param identity LFAIdentity object to be verified
   * @returns True if the identity matches what is on the sigchain
   */
  public async verifyIdentity(identity: LFAIdentity): Promise<boolean> {
    try {
      this.getUserAndChain(identity.id, identity.teamId)
      return true
    } catch (e) {
      const err = new LFAIdentityProviderVerifyError(e)
      this.logger.error('Error while verifying OrbitDB identity with LFA', err)
      return false
    }
  }

  /**
   * Validate a user is on the sigchain given a user ID and return the user record and chain
   *
   * @param userId LFA user ID
   * @param teamId LFA team ID
   * @param includeRemoved Include user record even if user is removed
   * @returns User and sigchain
   */
  public getUserAndChain(userId: string, teamId: string, includeRemoved: boolean = false): LFAUserAndChain {
    const sigchain = this.sigchainService.getChain({ teamId }, true)
    const user = sigchain.users.getUserById(userId, { includeRemoved, throwOnMissing: true })
    return {
      user: user!,
      sigchain,
    }
  }

  /**
   * Sign an arbitrary packet of data with your current LFA signature key
   *
   * @param userId LFA user ID
   * @param teamId LFA team ID
   * @param payload Data to be signed
   * @returns Hex representation of the signed envelope generated by LFA
   */
  public sign(userId: string, teamId: string, payload: any): string {
    try {
      // validate your user is on the chain
      const { user, sigchain } = this.getUserAndChain(userId, teamId)
      // ensure the user on the chain matches the user in our context
      const userFromContext = sigchain.context.user
      if (userFromContext.userId !== user.userId) {
        throw new Error('User ID and/or public signing key does not match context user')
      }
      // sign the payload and convert the signed envelope to a hex string
      const signedEnvelope = sigchain.crypto.sign(payload)
      return this._signedEnvelopeToHex({ signature: signedEnvelope.signature, author: signedEnvelope.author, teamId })
    } catch (e) {
      throw new LFAIdentityProviderSignError(e)
    }
  }

  /**
   * Verify an LFA signature on an OrbitDB log entry
   *
   * @param signature Hex representation of the signed envelope generated by LFA
   * @param publicKey Unused
   * @param data Data packet that was signed
   * @returns True if the signature is valid
   */
  public verify(signature: string, publicKey: string, data: string): boolean {
    try {
      // convert the hex string back to a signed envelope
      const signedEnvelope = this._hexToSignedEnvelope(signature)
      // validate the user is on the chain
      const { user, sigchain } = this.getUserAndChain(signedEnvelope.author.name, signedEnvelope.teamId)
      // verify the signature against the keys stored on the chain for this user
      return sigchain.crypto.validateSignature({ ...signedEnvelope, contents: data })
    } catch (e) {
      this.logger.error('Error validating OrbitDB entry signature', e)
      return false
    }
  }

  /**
   * Generate a reproducible signature for a given user's keys
   *
   * @param user User record from sigchain
   * @returns Payload string for signing
   */
  private _generateIdentitySignaturePayload(user: Member): string {
    return hash(user.userId, user.keys.signature)
  }

  /**
   * Serialize an LFA signed envelope and convert to a hex string
   *
   * @param signedEnvelope LFA signed envelope
   * @returns Hex representation of the signed envelope
   */
  private _signedEnvelopeToHex(signedEnvelope: SignatureWithTeamId): string {
    return uint8arrays.toString(this.serializer.serialize(signedEnvelope, SerializerEncodingType.UINT8ARRAY), 'hex')
  }

  /**
   * Serialize the hex and deserialize to the original signed envelope
   *
   * @param hexSignedEnvelope Hex representation of LFA signed envelope
   * @returns Deserialized signed envelope
   */
  private _hexToSignedEnvelope(hexSignedEnvelope: string): SignatureWithTeamId {
    return this.serializer.deserialize<SignatureWithTeamId>(uint8arrays.fromString(hexSignedEnvelope, 'hex'))
  }
}

export { LFAIdentityProvider }
