export enum ScreenNames {
  ChannelListScreen = 'ChannelList',
  ChannelScreen = 'ChannelScreen',
  ConnectionProcessScreen = 'ConnectionProcessScreen',
  DuplicatedUsernameScreen = 'DuplicatedUsernameScreen',
  UsernameTakenScreen = 'UsernameTakenScreen',
  NewUsernameRequestedScreen = 'NewUsernameRequestedScreen',
  PossibleImpersonationAttackScreen = 'PossibleImpersonationAttackScreen',
  CreateChannelScreen = 'CreateChannelScreen',
  CreateCommunityScreen = 'CreateCommunityScreen',
  DeleteChannelScreen = 'DeleteChannelScreen',
  ErrorScreen = 'ErrorScreen',
  JoinCommunityScreen = 'JoinCommunityScreen',
  LeaveCommunityScreen = 'LeaveCommunityScreen',
  NotifierScreen = 'NotifierScreen',
  QRCodeScreen = 'QRCodeScreen',
  SplashScreen = 'SplashScreen',
  SuccessScreen = 'SuccessScreen',
  UsernameRegistrationScreen = 'UsernameRegistrationScreen',
}
