export enum ScreenNames {
  SuccessScreen = 'SuccessScreen',
  ErrorScreen = 'ErrorScreen',
  SplashScreen = 'SplashScreen',
  CreateCommunityScreen = 'CreateCommunityScreen',
  JoinCommunityScreen = 'JoinCommunityScreen',
  UsernameRegistrationScreen = 'UsernameRegistrationScreen',
  ChannelListScreen = 'ChannelList',
  ChannelScreen = 'ChannelScreen',
  CreateChannelScreen = 'CreateChannelScreen',
  DeleteChannelScreen = 'DeleteChannelScreen',
  QRCodeScreen = 'QRCodeScreen',
  LeaveCommunityScreen = 'LeaveCommunityScreen',
  ConnectionProcessScreen = 'ConnectionProcessScreen',
  DuplicatedUsernameScreen = 'DuplicatedUsernameScreen',
  UnregisteredUsernameScreen = 'UnregisteredUsernameScreen',
  UsernameTakenScreen = 'UsernameTakenScreen',
  NewUsernameRequestedScreen = 'NewUsernameRequestedScreen',
}
