export enum ModalName {
  applicationUpdate = 'applicationUpdate',
  addModerator = 'addModerator',
  createChannel = 'createChannel',
  accountSettingsModal = 'accountSettingsModal',
  openexternallink = 'openexternallink',
  seedModal = 'seedModal',
  criticalError = 'criticalError',
  createUsernameModal = 'createUsernameModal',
  channelInfo = 'channelInfo',
  channelSettingsModal = 'channelSettingsModal',
  publishChannel = 'publishChannel',
  joinChannel = 'joinChannel',
  newMessageSeparate = 'newMessageSeparate',
  quitApp = 'quitApp',
  lightWalletSecurityModal = 'lightWalletSecurityModal',
  joinCommunityModal = 'joinCommunityModal',
  createCommunityModal = 'createCommunityModal',
  sentryWarningModal = 'sentryWarningModal',
  loadingPanel = 'loadingPanel'
}
