const test = require('node:test')
const assert = require('node:assert/strict')
const profiler = require('./runtime.cjs')
test('timed crypto-style calls preserve return values, receiver, nesting and rejection', async () => {
  profiler.reset()
  const inner = profiler.sync('inner', x => x + 1)
  const obj = {offset: 7, run: profiler.sync('outer', function (x) { return this.offset + inner(x) })}
  assert.equal(obj.run(2), 10)
  const failure = new Error('invalid ciphertext')
  assert.throws(profiler.sync('invalid', () => {throw failure}), error => error === failure)
  const result = await profiler.asyncSpan('consume', async x => obj.run(x))(3)
  assert.equal(result, 11)
  const metrics = profiler.snapshot()
  assert.equal(metrics.inner.calls, 2)
  assert.equal(metrics.outer.calls, 2)
  assert.equal(metrics.invalid.errors, 1)
  assert.equal(metrics['consume.wall'].calls, 1)
  assert.ok(metrics.outer.totalMs >= metrics.outer.selfMs)
  profiler.setEnabled(false)
  assert.equal(obj.run(4), 12)
  assert.equal(profiler.snapshot().outer.calls, 2)
  profiler.setEnabled(true)
})
