// GENERATED by design-system/flow/gen.cjs from figma/flow.json — do not hand-edit.
// One story per screen reachable from "Get started" via the prototype's own links.
// Export names are chosen so Storybook's derived id equals `onboarding-flow--<slug>`; gen.cjs asserts it.
import React from 'react'

import flowJson from '../figma/flow.json'
import { DesktopDesigns, Flow, FlowMap, FLOW_TITLE, Stage } from '../flow/FigmaFlow'

const flow = flowJson as Flow
const frame = (slug: string) => flow.frames.find(f => f.slug === slug)!

export default {
  title: FLOW_TITLE,
  parameters: { layout: 'fullscreen', chromatic: { disableSnapshot: true } },
}

export const AllStages = () => <FlowMap flow={flow} />
AllStages.storyName = '— all stages —'

export const DesktopDesigns_ = () => <DesktopDesigns flow={flow} />
DesktopDesigns_.storyName = 'Desktop — designs'

export const GetStarted = () => <Stage flow={flow} frame={frame("get-started")} />
GetStarted.storyName = "Get started"

export const JoinCommunity = () => <Stage flow={flow} frame={frame("join-community")} />
JoinCommunity.storyName = "Join community"

export const CreateDefault = () => <Stage flow={flow} frame={frame("create-default")} />
CreateDefault.storyName = "Create a community"

export const LinkDevices = () => <Stage flow={flow} frame={frame("link-devices")} />
LinkDevices.storyName = "Link devices"

export const OpenInviteLink = () => <Stage flow={flow} frame={frame("open-invite-link")} />
OpenInviteLink.storyName = "Join with invite link"

export const Sheet_2811_2460 = () => <Stage flow={flow} frame={frame("sheet-2811-2460")} />
Sheet_2811_2460.storyName = "Join with QR code (sheet)"

export const RecoverAccountInfo = () => <Stage flow={flow} frame={frame("recover-account-info")} />
RecoverAccountInfo.storyName = "Recover account"

export const Sheet_2811_2601 = () => <Stage flow={flow} frame={frame("sheet-2811-2601")} />
Sheet_2811_2601.storyName = "Link devices — display QR code (sheet)"

export const Sheet_2811_2587 = () => <Stage flow={flow} frame={frame("sheet-2811-2587")} />
Sheet_2811_2587.storyName = "Link devices — scan QR code (sheet)"

export const Container = () => <Stage flow={flow} frame={frame("container")} />
Container.storyName = "Paste a link to Join (WIP)"

export const CropPhoto_3 = () => <Stage flow={flow} frame={frame("crop-photo-3")} />
CropPhoto_3.storyName = "Crop photo"

export const UsernameDefault = () => <Stage flow={flow} frame={frame("username-default")} />
UsernameDefault.storyName = "Choose username"

export const UsernamePopulated = () => <Stage flow={flow} frame={frame("username-populated")} />
UsernamePopulated.storyName = "Choose username — name typed"

export const JoinPhotoNameTrue_2811_2366 = () => <Stage flow={flow} frame={frame("join-photo-name-true-2811-2366")} />
JoinPhotoNameTrue_2811_2366.storyName = "Create a community — filled"

export const CommunityHome = () => <Stage flow={flow} frame={frame("community-home")} />
CommunityHome.storyName = "Community home"

export const CommunitySwitcher_2853_1955 = () => <Stage flow={flow} frame={frame("community-switcher-2853-1955")} />
CommunitySwitcher_2853_1955.storyName = "Community switcher"

export const WantAServer = () => <Stage flow={flow} frame={frame("want-a-server")} />
WantAServer.storyName = "Want a server?"

export const ChooseAPlan = () => <Stage flow={flow} frame={frame("choose-a-plan")} />
ChooseAPlan.storyName = "Choose a plan"

export const NoServer = () => <Stage flow={flow} frame={frame("no-server")} />
NoServer.storyName = "No server?"

export const AgreeAndJoinServerOptIn_3054_4090 = () => <Stage flow={flow} frame={frame("agree-and-join-server-opt-in-3054-4090")} />
AgreeAndJoinServerOptIn_3054_4090.storyName = "Agree & join — server opt-in"

export const Captcha_3054_4052 = () => <Stage flow={flow} frame={frame("captcha-3054-4052")} />
Captcha_3054_4052.storyName = "Captcha"

export const HomeAddMembers = () => <Stage flow={flow} frame={frame("home-add-members")} />
HomeAddMembers.storyName = "Community home — add members"

export const AddMembersOptions = () => <Stage flow={flow} frame={frame("add-members-options")} />
AddMembersOptions.storyName = "Add members"

export const AddMembersQrCode = () => <Stage flow={flow} frame={frame("add-members-qr-code")} />
AddMembersQrCode.storyName = "Add members — QR code"

export const AgreeAndJoinV_1BeforeWeSupportMultipleHosts = () => <Stage flow={flow} frame={frame("agree-and-join-v-1-before-we-support-multiple-hosts")} />
AgreeAndJoinV_1BeforeWeSupportMultipleHosts.storyName = "Agree & join — joiner (v1)"
