name: Check

on:
  pull_request:

jobs:
  check:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: "Remove test files workaround (jest types conflicting with cypress types)"
        if: ${{ runner.os == 'Windows' }}
        run: find packages/desktop/src -name '*.test.*' -delete
        shell: bash

      - name: "Setup environment for Linux and MacOS"
        uses: ./.github/actions/setup-env
        if: ${{ runner.os != 'Windows' }}

      - name: "Setup environment for Windows"
        uses: ./.github/actions/setup-env
        if: ${{ runner.os == 'Windows' }}

      - name: "Lint"
        if: ${{ runner.os != 'Windows' }}
        run: npm run lint:all:ci
