name: Desktop visual regressions

on:
  pull_request:

jobs:
  chromatic-deployment:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            desktop:
              - 'packages/desktop/**'
      - name: "Skip tests"
        run: |
         echo "Skipping test run"
        #

      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/desktop,backend-bundle"

      - name: "Publish to Chromatic"
        uses: chromaui/action@355e2a05a179e9e89c2b237dcd55adbeb89e577e # v1
        with:
          workingDir: ./packages/desktop
          token: ${{ secrets.GH_TOKEN }}
          projectToken: 3218757eee04
