name: Desktop - state-manager bracket tests (RTL)

on:
  pull_request:

jobs:
  desktop-tests:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]

    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            validFiles:
              - 'packages/desktop/**'
              - 'packages/state-manger/**'
      - name: "Skip tests"
        if: steps.filter.outputs.validFiles == 'false'
        run: |
         echo "Skipping test run" 
         exit 0

      - name: "Print OS"
        if: steps.filter.outputs.validFiles == 'true'
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v3
        if: steps.filter.outputs.validFiles == 'true'

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        if: steps.filter.outputs.validFiles == 'true'
        with:
          cachePrefix: "desktop-tests"
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/desktop,backend-bundle"

      - name: "Desktop - state-manager bracket tests"
        if: steps.filter.outputs.validFiles == 'true'
        run: lerna run rtl-test --scope @quiet/desktop --stream
