name: E2E iOS

on:
  pull_request:
    paths:
      - packages/mobile/**

jobs:
  detox:
    timeout-minutes: 25
    runs-on: self-hosted

    steps:

      - name: Run basic tests
        run: |
          cd ~/projects/quiet/packages/mobile
          detox test starter -c ios.sim.debug
