name: E2E cross platform

on: 
  pull_request:
    paths:
      - packages/desktop/**
      - packages/backend/**
      - packages/state-manager/**
      - packages/identity/**
      - packages/common/**
      - packages/e2e-tests/**
      - 3rd-party/**
      - .github/workflows/e2e**
      - .github/actions/setup-env/**
      - .github/actions/before-build/**

jobs:
  mac:
    uses: ./.github/workflows/e2e-mac.yml
  linux:
    uses: ./.github/workflows/e2e-linux.yml
  linux-qss:
    uses: ./.github/workflows/e2e-qss-linux.yml
  linux-back-compat:
    uses: ./.github/workflows/e2e-back-compat-linux.yml
  # windows:
  #   uses: ./.github/workflows/e2e-win.yml
    
