name: E2E with QSS Mac

on: [workflow_call]
jobs:
  mac:
    runs-on: macos-13
    timeout-minutes: 180
    env:
      TEST_MODE: true
      IS_E2E: true
      IS_CI: true

    steps:
      - name: "Setup and build app image"
        uses: ./.github/actions/e2e-build-mac
        with:
          is-arm: ${{ runner.arch == 'ARM' || runner.arch == 'ARM64' }}

      - name: Start QSS docker
        run: npm run start:qss

      - name: Run multiple clients with QSS test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test multipleClients.qss.test.ts

      - name: Stop QSS docker
        if: always()
        run: npm run stop:qss
