name: E2E Mac

on: [workflow_call]
jobs:
  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            binary_suffix: "-arm64"
          - os: macos-26-intel
            binary_suffix: ""

    timeout-minutes: 180
    env:
      TEST_MODE: true
      IS_E2E: true
      IS_CI: true

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          install-docker: false
          cachePrefix: "e2e-crossplatform-mac"
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/desktop,backend-bundle,e2e-tests,helia,@quiet/node-common"

      - name: Before build
        uses: ./.github/actions/before-build
        with:
          source-path: darwin
          envfile: .env.e2e

      - name: Build App Image
        working-directory: ./packages/desktop
        run: node_modules/.bin/electron-builder --mac

      - name: VERSION env
        working-directory: ./packages/desktop
        run: echo "VERSION=$(jq -r ".version" package.json)" >> $GITHUB_ENV

      - name: FILE_NAME env
        working-directory: ./packages/desktop/dist
        run: echo "FILE_NAME="Quiet-$VERSION${{matrix.binary_suffix}}.dmg"" >> $GITHUB_ENV

      - name: List dist dir content
        working-directory: ./packages/desktop/dist
        run: ls -al

      - name: Chmod
        working-directory: ./packages/desktop/dist
        run: chmod +x $FILE_NAME

      - name: Mount installer file in volume on system
        working-directory: ./packages/desktop/dist
        run: hdiutil mount $FILE_NAME

      - name: Add App file to applications
        id: finish-test-prep
        run: cd ~ && cp -R "/Volumes/Quiet $VERSION${{matrix.binary_suffix}}/Quiet.app" /Applications

      - name: Run one client test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test oneClient.test.ts

      - name: Run user profile test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        if: steps.finish-test-prep.outcome == 'success'
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test userProfile.test.ts

      - name: Run multiple clients test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        if: steps.finish-test-prep.outcome == 'success'
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test multipleClients.test.ts
      
      - name: Run multiple clients test (private channels)
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        if: steps.finish-test-prep.outcome == 'success'
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test multipleClients.privateChannels.test.ts

      - name: Run invitation link test - Includes 2 separate application clients
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        if: steps.finish-test-prep.outcome == 'success'
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test invitationLink.test.ts
