name: New E2E tests

on:
  pull_request:

jobs:
  new-e2e-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/logger,@quiet/state-manager,@quiet/backend,@quiet/identity,quiet,integration-tests,testcafe-browser-provider-electron,e2e-tests"

      - name: Build image
        run: cd packages/e2e-tests/tests && docker build -t e2e-test-image .   

      - name: Download AppImage
        run: cd packages/e2e-tests/tests/Quiet && curl -LO https://github.com/TryQuiet/quiet/releases/download/quiet%400.16.0/Quiet-0.16.0.AppImage

      - name: Chmod
        run: cd packages/e2e-tests/tests/Quiet && chmod +x Quiet-0.16.0.AppImage

      - name: Run tests
        run: cd packages/e2e-tests/tests && npm run test smoke.test.ts
