name: E2E iOS

on:
  pull_request:
    paths:
      - packages/mobile/**

jobs:
  detox:
    timeout-minutes: 25
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm i
          npm run lerna bootstrap --scope @quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/mobile,backend-bundle

      - name: Pull binaries
        run: |
          git lfs install
          git lfs pull

      - name: Install pods
        run: |
          cd packages/mobile/ios
          pod install

      - name: Build Detox
        run: |
          cd packages/mobile
          detox build -c ios.sim.debug

      - name: Run basic tests
        run: |
          cd packages/mobile
          detox test starter -c ios.sim.debug
