name: Mobile tests

on:
  pull_request:
    paths:
      - packages/mobile/**

jobs:
  desktop-tests:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/mobile,backend-bundle"

      - name: "Unit tests"
        run: lerna run test --scope @quiet/mobile --stream
