name: Build Android Package Kit

on:
  release:
    types:
      [prereleased, released]

jobs:
  build-android-package-kit:
    # needs: detox-android
    runs-on: ${{ matrix.os }}
    if: |
      startsWith(github.ref, 'refs/tags/@quiet/mobile')

    strategy:
      matrix:
        os: [ubuntu-latest-m]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Set up JDK"
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: "Set up NDK"
        uses: nttld/setup-ndk@8c3b609ff4d54576ea420551943fd34b4d03b0dc # v1.2.0
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/mobile,backend-bundle"

      - name: "Create gradle configuration directory"
        run: mkdir -p $HOME/.gradle

      - name: "Prepare ndk configuration"
        run: |
          printf "\
          NDK_PATH=${{ steps.setup-ndk.outputs.ndk-path }}\n\
          " > $HOME/.gradle/gradle.properties

      - name: "Prepare signing configuration"
        run: |
          printf "\
          STORE_FILE=quietmobile.keystore\n\
          STORE_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\n\
          KEY_ALIAS=${{ SECRETS.GOOGLE_KEYSTORE_ALIAS }}\n\
          KEY_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\
          " >> $HOME/.gradle/gradle.properties

      - name: "Decode keystore"
        run: echo ${{ SECRETS.GOOGLE_KEYSTORE }} | base64 --decode > ./packages/mobile/android/app/quietmobile.keystore

      - name: "Build .apk"
        run: cd ./packages/mobile/android && ENVFILE=../.env.production ./gradlew assembleStandardRelease

      - name: "Upload .apk to artifacts"
        continue-on-error: true
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: app-standard-release.apk
          path: ./packages/mobile/android/app/build/outputs/apk/standard/release/app-standard-release.apk

      - name: "Get release"
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "Upload release assets"
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./packages/mobile/android/app/build/outputs/apk/standard/release/app-standard-release.apk
          asset_name: app-standard-release.apk
          asset_content_type: application/.apk
