name: Scroll regression tests

on:
  pull_request:
    paths:
      - packages/desktop/**

jobs:
  regression-tests:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,quiet,backend-bundle"

      - name: "Install libs"
        run: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: "Remove test files workaround"
        run: find packages/desktop/src -name '*.test.*' -delete && find packages/backend/src -name '*.test.*' -delete

      - uses: cypress-io/github-action@f5bea478b80a774068179089247f13d60abc5010 # v2.11.8
        with:
          install: false
          command: npm run regression-test:ci
          working-directory: packages/desktop

      - name: Archive test screenshots
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        if: always()
        with:
          name: test-screenshots-linux
          path: packages/desktop/cypress/snapshots