export enum MessageType {
  BASIC = 1,
  AD = 2,
  TRANSFER = 4,
  USER = 5,
  CHANNEL_SETTINGS = 6,
  MODERATION = 7,
  PUBLISH_CHANNEL = 8,
  ITEM_BASIC = 11,
  ITEM_TRANSFER = 41,
  USER_V2 = 51,
  CHANNEL_SETTINGS_UPDATE = 61,
  AFFILIATE = 170, // 'aa' in hex
  CONNECTION_ESTABLISHED = 200
}
